export const PENDING_CONTACT_STATUS = "PENDING";
export const ATTENDED_CONTACT_STATUS = "ATTENDED";
export const SPAM_CONTACT_STATUS = "SPAM";

export const CONTACT_STATUSES = [
  PENDING_CONTACT_STATUS,
  ATTENDED_CONTACT_STATUS,
  SPAM_CONTACT_STATUS,
];
